server:
  port: 9527

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring.data.mongodb.uri: mongodb://127.0.0.1:27017/thoughtworks
